using Microsoft.CodeAnalysis;
using System.CodeDom.Compiler;

namespace Minimal.Mvvm.SourceGenerator;

internal static class IndentedTextWriterExtensions
{
    public static void WriteSourceHeader(this IndentedTextWriter writer, NullableContextOptions nullableContextOptions)
    {
        writer.WriteLine($"""
                          // <auto-generated>
                          //     Auto-generated by Minimal.Mvvm.SourceGenerator {typeof(Generator).Assembly.GetName().Version}
                          // </auto-generated>
                          """);
        writer.WriteLine();

        if (nullableContextOptions != NullableContextOptions.Disable)
        {
            writer.WriteNullableContext(nullableContextOptions);
            writer.WriteLine();
        }
    }

    public static void WriteNamespaceStart(this IndentedTextWriter writer, string? containingNamespace)
    {
        if (!string.IsNullOrEmpty(containingNamespace))//begin namespace
        {
            writer.WriteLine($"namespace {containingNamespace}");
            writer.WriteLine("{");
            writer.Indent++;
        }
    }

    public static void WriteSourceNamespaceEnd(this IndentedTextWriter writer, string? containingNamespace)
    {
        if (!string.IsNullOrEmpty(containingNamespace))//end namespace
        {
            writer.Indent--;
            writer.WriteLine("}");
        }
    }

    public static void WriteAccessibility(this IndentedTextWriter writer, Accessibility accessibility)
    {
        switch (accessibility)
        {
            case Accessibility.Public:
                writer.Write("public ");
                break;
            case Accessibility.ProtectedOrInternal:
                writer.Write("protected internal ");
                break;
            case Accessibility.Internal:
                writer.Write("internal ");
                break;
            case Accessibility.Protected:
                writer.Write("protected ");
                break;
            case Accessibility.ProtectedAndInternal:
                writer.Write("private protected ");
                break;
            case Accessibility.Private:
                writer.Write("private ");
                break;
        }
    }

    public static void WriteNullableContext(this IndentedTextWriter writer, NullableContextOptions nullableContextOptions)
    {
        switch (nullableContextOptions)
        {
            case NullableContextOptions.Disable:
                writer.WriteLine("#nullable disable");
                break;
            case NullableContextOptions.Warnings:
                writer.WriteLine("#nullable enable warnings");
                break;
            case NullableContextOptions.Annotations:
                writer.WriteLine("#nullable enable annotations");
                break;
            case NullableContextOptions.Enable:
                writer.WriteLine("#nullable enable");
                break;
        }
    }
}
