namespace NuExt.Minimal.Mvvm.SourceGenerator.Tests
{
    internal static partial class AccessModifiers
    {
        public static List<(string source, string? expected)> Sources =
        [
            (
                source : """
                using Minimal.Mvvm;

                public partial class MyModel : System.ComponentModel.INotifyPropertyChanged
                {
                    [Notify]
                    private string _name = null!;

                    [Notify]
                    private string? _description;

                    public event System.ComponentModel.PropertyChangedEventHandler? PropertyChanged;
                }
                """,
                expected : null),
            (
                source : """
                using Minimal.Mvvm;

                public partial class MyModel : BindableBase
                {
                    [Notify]
                    private string _name = null!;

                    [Notify]
                    private string? _description;
                }
                """,
                expected : """
                // <auto-generated>
                //     Auto-generated by [GeneratorName] [GeneratorVersion]
                // </auto-generated>

                #nullable enable

                partial class MyModel
                {
                    public string Name
                    {
                        get => _name;
                        set => SetProperty(ref _name, value, global::Minimal.Mvvm.EventArgsCache.NamePropertyChanged);
                    }

                    public string? Description
                    {
                        get => _description;
                        set => SetProperty(ref _description, value, global::Minimal.Mvvm.EventArgsCache.DescriptionPropertyChanged);
                    }
                }
                """ ),
            (
                source : """
                using Minimal.Mvvm;

                public partial class MyModel : ViewModelBase
                {
                    [Notify(Setter = AccessModifier.Private)]
                    private string _name = null!;

                    [Notify(Getter = AccessModifier.Internal)]
                    private string? _description;
                }
                """, 
                expected: """
                // <auto-generated>
                //     Auto-generated by [GeneratorName] [GeneratorVersion]
                // </auto-generated>

                #nullable enable

                partial class MyModel
                {
                    public string Name
                    {
                        get => _name;
                        private set => SetProperty(ref _name, value, global::Minimal.Mvvm.EventArgsCache.NamePropertyChanged);
                    }

                    internal string? Description
                    {
                        get => _description;
                        set => SetProperty(ref _description, value, global::Minimal.Mvvm.EventArgsCache.DescriptionPropertyChanged);
                    }
                }
                """),
            (
                source: """
                using Minimal.Mvvm;

                public partial class MyModel : ViewModelBase
                {
                    [Notify(Setter = AccessModifier.ProtectedInternal)]
                    private string _name = null!;

                    [Notify(Getter = AccessModifier.Internal, Setter = AccessModifier.Private)]
                    private string? _description;
                }
                """, 
                expected: """
                // <auto-generated>
                //     Auto-generated by [GeneratorName] [GeneratorVersion]
                // </auto-generated>

                #nullable enable

                partial class MyModel
                {
                    public string Name
                    {
                        get => _name;
                        protected internal set => SetProperty(ref _name, value, global::Minimal.Mvvm.EventArgsCache.NamePropertyChanged);
                    }

                    internal string? Description
                    {
                        get => _description;
                        private set => SetProperty(ref _description, value, global::Minimal.Mvvm.EventArgsCache.DescriptionPropertyChanged);
                    }
                }
                """),
            (
                source: """
                using Minimal.Mvvm;

                public partial class MyModel : ViewModelBase
                {
                    [Notify(Getter = AccessModifier.Private, Setter = AccessModifier.ProtectedInternal)]
                    private string _name = null!;

                    [Notify(Getter = AccessModifier.Internal, Setter = AccessModifier.PrivateProtected)]
                    private string? _description;
                }
                """,
                expected: """
                // <auto-generated>
                //     Auto-generated by [GeneratorName] [GeneratorVersion]
                // </auto-generated>

                #nullable enable

                partial class MyModel
                {
                    protected internal string Name
                    {
                        private get => _name;
                        set => SetProperty(ref _name, value, global::Minimal.Mvvm.EventArgsCache.NamePropertyChanged);
                    }

                    internal string? Description
                    {
                        get => _description;
                        private protected set => SetProperty(ref _description, value, global::Minimal.Mvvm.EventArgsCache.DescriptionPropertyChanged);
                    }
                }
                """),
            (
                source: """
                using Minimal.Mvvm;

                public partial class MyModel : ViewModelBase
                {
                    [Notify(Getter = AccessModifier.Private, Setter = AccessModifier.Private)]
                    private string _name = null!;

                    [Notify(Getter = AccessModifier.Private, Setter = AccessModifier.Internal)]
                    private string? _description;
                }
                """,
                expected: """
                // <auto-generated>
                //     Auto-generated by [GeneratorName] [GeneratorVersion]
                // </auto-generated>

                #nullable enable

                partial class MyModel
                {
                    private string Name
                    {
                        get => _name;
                        set => SetProperty(ref _name, value, global::Minimal.Mvvm.EventArgsCache.NamePropertyChanged);
                    }

                    internal string? Description
                    {
                        private get => _description;
                        set => SetProperty(ref _description, value, global::Minimal.Mvvm.EventArgsCache.DescriptionPropertyChanged);
                    }
                }
                """),
            (
                source: """
                using Minimal.Mvvm;

                public partial class MyModel : ViewModelBase
                {
                    [Notify(Getter = AccessModifier.Private, Setter = AccessModifier.Public)]
                    private string _name = null!;

                    [Notify(Getter = AccessModifier.Private, Setter = AccessModifier.PrivateProtected)]
                    private string? _description;
                }
                """,
                expected: """
                // <auto-generated>
                //     Auto-generated by [GeneratorName] [GeneratorVersion]
                // </auto-generated>

                #nullable enable

                partial class MyModel
                {
                    public string Name
                    {
                        private get => _name;
                        set => SetProperty(ref _name, value, global::Minimal.Mvvm.EventArgsCache.NamePropertyChanged);
                    }

                    private protected string? Description
                    {
                        private get => _description;
                        set => SetProperty(ref _description, value, global::Minimal.Mvvm.EventArgsCache.DescriptionPropertyChanged);
                    }
                }
                """),
            (
                source: """
                using Minimal.Mvvm;

                public partial class MyModel : ViewModelBase
                {
                    [Notify(Getter = AccessModifier.Internal, Setter = AccessModifier.Protected)]
                    private string _name = null!;

                    [Notify(Getter = AccessModifier.Protected, Setter = AccessModifier.Internal)]
                    private string? _description;
                }
                """,
                expected: """
                // <auto-generated>
                //     Auto-generated by [GeneratorName] [GeneratorVersion]
                // </auto-generated>

                #nullable enable

                partial class MyModel
                {
                    protected internal string Name
                    {
                        get => _name;
                        protected set => SetProperty(ref _name, value, global::Minimal.Mvvm.EventArgsCache.NamePropertyChanged);
                    }

                    protected internal string? Description
                    {
                        get => _description;
                        internal set => SetProperty(ref _description, value, global::Minimal.Mvvm.EventArgsCache.DescriptionPropertyChanged);
                    }
                }
                """),
            (
                source: """
                using Minimal.Mvvm;

                public partial class MyModel : ViewModelBase
                {
                    [Notify(Getter = AccessModifier.ProtectedInternal, Setter = AccessModifier.Protected)]
                    private string _name = null!;

                    [Notify(Getter = AccessModifier.ProtectedInternal, Setter = AccessModifier.Internal)]
                    private string? _description;
                }
                """,
                expected: """
                // <auto-generated>
                //     Auto-generated by [GeneratorName] [GeneratorVersion]
                // </auto-generated>

                #nullable enable

                partial class MyModel
                {
                    protected internal string Name
                    {
                        get => _name;
                        protected set => SetProperty(ref _name, value, global::Minimal.Mvvm.EventArgsCache.NamePropertyChanged);
                    }

                    protected internal string? Description
                    {
                        get => _description;
                        internal set => SetProperty(ref _description, value, global::Minimal.Mvvm.EventArgsCache.DescriptionPropertyChanged);
                    }
                }
                """),
            (
                source: """
                using Minimal.Mvvm;

                public partial class MyModel : ViewModelBase
                {
                    [Notify(Getter = AccessModifier.Internal, Setter = AccessModifier.ProtectedInternal)]
                    private string _name = null!;

                    [Notify(Getter = AccessModifier.Protected, Setter = AccessModifier.ProtectedInternal)]
                    private string? _description;
                }
                """,
                expected: """
                // <auto-generated>
                //     Auto-generated by [GeneratorName] [GeneratorVersion]
                // </auto-generated>

                #nullable enable

                partial class MyModel
                {
                    protected internal string Name
                    {
                        internal get => _name;
                        set => SetProperty(ref _name, value, global::Minimal.Mvvm.EventArgsCache.NamePropertyChanged);
                    }

                    protected internal string? Description
                    {
                        protected get => _description;
                        set => SetProperty(ref _description, value, global::Minimal.Mvvm.EventArgsCache.DescriptionPropertyChanged);
                    }
                }
                """),
        ];
    }
}
