namespace NuExt.Minimal.Mvvm.SourceGenerator.Tests;

internal partial class Commands
{
    public static List<(string source, string? expected)> CancellationSources =
    [
        ( 
        source : """
        using Minimal.Mvvm;
        using System.Threading;
        using System.Threading.Tasks;
        
        public partial class MyViewModel : ViewModelBase
        {
            [Notify(Setter = AccessModifier.Private)]
            private async Task OpenAsync(CancellationToken ct)
            {
                await Task.Delay(1000);
            }

            [Notify(Setter = AccessModifier.Private)]
            private async Task CloseAsync(bool force, CancellationToken ct)
            {
                await Task.Delay(1000);
            }

            [Notify(Setter = AccessModifier.Private)]
            private void Hide(CancellationToken ct)
            {
            }
        }
        """, 
        expected: """
        // <auto-generated>
        //     Auto-generated by [GeneratorName] [GeneratorVersion]
        // </auto-generated>
        
        #nullable enable

        partial class MyViewModel
        {
            private global::Minimal.Mvvm.IAsyncCommand? _openCommand;
            public global::Minimal.Mvvm.IAsyncCommand? OpenCommand
            {
                get => _openCommand;
                private set => SetProperty(ref _openCommand, value, global::Minimal.Mvvm.EventArgsCache.OpenCommandPropertyChanged);
            }

            private global::Minimal.Mvvm.IAsyncCommand<bool>? _closeCommand;
            public global::Minimal.Mvvm.IAsyncCommand<bool>? CloseCommand
            {
                get => _closeCommand;
                private set => SetProperty(ref _closeCommand, value, global::Minimal.Mvvm.EventArgsCache.CloseCommandPropertyChanged);
            }

            private global::Minimal.Mvvm.IRelayCommand<global::System.Threading.CancellationToken>? _hideCommand;
            public global::Minimal.Mvvm.IRelayCommand<global::System.Threading.CancellationToken>? HideCommand
            {
                get => _hideCommand;
                private set => SetProperty(ref _hideCommand, value, global::Minimal.Mvvm.EventArgsCache.HideCommandPropertyChanged);
            }
        }
        """
        )
    ];
   
}
