namespace NuExt.Minimal.Mvvm.SourceGenerator.Tests;

internal partial class Commands
{
    public static List<(string source, string? expected)> Sources =
    [
        (
            source : """
            using Minimal.Mvvm;
            using System.Windows.Input;

            public partial class MyViewModel : ViewModelBase
            {
                [Notify] private ICommand? _commandICommand;

                [Notify] private IRelayCommand? _commandIRelayCommand;
                [Notify] private IRelayCommand<bool>? _commandIRelayCommandT;
                [Notify] private IAsyncCommand? _commandIAsyncCommand;
                [Notify] private IAsyncCommand<bool>? _commandIAsyncCommandT;

                [Notify] private RelayCommand? _commandRelayCommand;
                [Notify] private RelayCommand<bool>? _commandRelayCommandT;
                [Notify] private AsyncCommand? _commandAsyncCommand;
                [Notify] private AsyncCommand<bool>? _commandAsyncCommandT;
            }
            """,
            expected : """
             // <auto-generated>
             //     Auto-generated by [GeneratorName] [GeneratorVersion]
             // </auto-generated>
             
             #nullable enable
             
             partial class MyViewModel
             {
                 public global::System.Windows.Input.ICommand? CommandICommand
                 {
                     get => _commandICommand;
                     set => SetProperty(ref _commandICommand, value, global::Minimal.Mvvm.EventArgsCache.CommandICommandPropertyChanged);
                 }
             
                 public global::Minimal.Mvvm.IRelayCommand? CommandIRelayCommand
                 {
                     get => _commandIRelayCommand;
                     set => SetProperty(ref _commandIRelayCommand, value, global::Minimal.Mvvm.EventArgsCache.CommandIRelayCommandPropertyChanged);
                 }
              
                 public global::Minimal.Mvvm.IRelayCommand<bool>? CommandIRelayCommandT
                 {
                     get => _commandIRelayCommandT;
                     set => SetProperty(ref _commandIRelayCommandT, value, global::Minimal.Mvvm.EventArgsCache.CommandIRelayCommandTPropertyChanged);
                 }

                 public global::Minimal.Mvvm.IAsyncCommand? CommandIAsyncCommand
                 {
                     get => _commandIAsyncCommand;
                     set => SetProperty(ref _commandIAsyncCommand, value, global::Minimal.Mvvm.EventArgsCache.CommandIAsyncCommandPropertyChanged);
                 }
                 public global::Minimal.Mvvm.IAsyncCommand<bool>? CommandIAsyncCommandT
                 {
                     get => _commandIAsyncCommandT;
                     set => SetProperty(ref _commandIAsyncCommandT, value, global::Minimal.Mvvm.EventArgsCache.CommandIAsyncCommandTPropertyChanged);
                 }
             
                 public global::Minimal.Mvvm.RelayCommand? CommandRelayCommand
                 {
                     get => _commandRelayCommand;
                     set => SetProperty(ref _commandRelayCommand, value, global::Minimal.Mvvm.EventArgsCache.CommandRelayCommandPropertyChanged);
                 }
                 public global::Minimal.Mvvm.RelayCommand<bool>? CommandRelayCommandT
                 {
                     get => _commandRelayCommandT;
                     set => SetProperty(ref _commandRelayCommandT, value, global::Minimal.Mvvm.EventArgsCache.CommandRelayCommandTPropertyChanged);
                 }
                 public global::Minimal.Mvvm.AsyncCommand? CommandAsyncCommand
                 {
                     get => _commandAsyncCommand;
                     set => SetProperty(ref _commandAsyncCommand, value, global::Minimal.Mvvm.EventArgsCache.CommandAsyncCommandPropertyChanged);
                 }
                 public global::Minimal.Mvvm.AsyncCommand<bool>? CommandAsyncCommandT
                 {
                     get => _commandAsyncCommandT;
                     set => SetProperty(ref _commandAsyncCommandT, value, global::Minimal.Mvvm.EventArgsCache.CommandAsyncCommandTPropertyChanged);
                 }
             }
             """
        ),
        (
            source : """
            using Minimal.Mvvm;
            using System.Threading.Tasks;

            public partial class MyViewModel : ViewModelBase
            {
                [Notify(Setter = AccessModifier.Private), CustomAttribute("[global::System.Text.Json.Serialization.JsonIgnore]")]
                private async global::System.Threading.Tasks.Task CloseAsync()
                {
                    await Task.Delay(1000);
                }

                /// <summary>
                /// Opens file.
                /// </summary>
                [Notify("OpenFileCommand", Setter = AccessModifier.Private), CustomAttribute("[global::System.Text.Json.Serialization.JsonIgnore]")]
                private async System.Threading.Tasks.Task OpenAsync(string? filePath)
                {
                    await Task.Delay(1000);
                }

                [Notify(Setter = AccessModifier.Private), CustomAttribute("[global::System.Text.Json.Serialization.JsonIgnore]")]
                private void Hide()
                {
                }

                [Notify("ShowAndActivateCommand", Setter = AccessModifier.Private), CustomAttribute("[global::System.Text.Json.Serialization.JsonIgnore]")]
                private void Show()
                {
                    ActivateCommand?.Execute(true);
                }

                [Notify(Setter = AccessModifier.Private), CustomAttribute("[global::System.Text.Json.Serialization.JsonIgnore]")]
                private void Activate(bool bringToFront)
                {
                }

                [Notify(Setter = AccessModifier.Private, CallbackName=nameof(OnChangeActiveViewModelCommandChanged)), CustomAttribute("[global::System.Text.Json.Serialization.JsonIgnore]")]
                private async Task ChangeActiveViewModelAsync(ViewModelBase? viewModel)
                {
                    await Task.Delay(1000);
                }

                private void OnChangeActiveViewModelCommandChanged(IAsyncCommand? command)
                {
                }
            }
            """,
            expected : """
            // <auto-generated>
            //     Auto-generated by [GeneratorName] [GeneratorVersion]
            // </auto-generated>

            #nullable enable

            partial class MyViewModel
            {
                private global::Minimal.Mvvm.IAsyncCommand? _closeCommand;
                [global::System.Text.Json.Serialization.JsonIgnore]
                public global::Minimal.Mvvm.IAsyncCommand? CloseCommand
                {
                    get => _closeCommand;
                    private set => SetProperty(ref _closeCommand, value, global::Minimal.Mvvm.EventArgsCache.CloseCommandPropertyChanged);
                }

                private global::Minimal.Mvvm.IAsyncCommand<string?>? _openFileCommand;
                /// <summary>
                /// Opens file.
                /// </summary>
                [global::System.Text.Json.Serialization.JsonIgnore]
                public global::Minimal.Mvvm.IAsyncCommand<string?>? OpenFileCommand
                {
                    get => _openFileCommand;
                    private set => SetProperty(ref _openFileCommand, value, global::Minimal.Mvvm.EventArgsCache.OpenFileCommandPropertyChanged);
                }

                private global::Minimal.Mvvm.IRelayCommand? _hideCommand;
                [global::System.Text.Json.Serialization.JsonIgnore]
                public global::Minimal.Mvvm.IRelayCommand? HideCommand
                {
                    get => _hideCommand;
                    private set => SetProperty(ref _hideCommand, value, global::Minimal.Mvvm.EventArgsCache.HideCommandPropertyChanged);
                }

                private global::Minimal.Mvvm.IRelayCommand? _showAndActivateCommand;
                [global::System.Text.Json.Serialization.JsonIgnore]
                public global::Minimal.Mvvm.IRelayCommand? ShowAndActivateCommand
                {
                    get => _showAndActivateCommand;
                    private set => SetProperty(ref _showAndActivateCommand, value, global::Minimal.Mvvm.EventArgsCache.ShowAndActivateCommandPropertyChanged);
                }

                private global::Minimal.Mvvm.IRelayCommand<bool>? _activateCommand;
                [global::System.Text.Json.Serialization.JsonIgnore]
                public global::Minimal.Mvvm.IRelayCommand<bool>? ActivateCommand
                {
                    get => _activateCommand;
                    private set => SetProperty(ref _activateCommand, value, global::Minimal.Mvvm.EventArgsCache.ActivateCommandPropertyChanged);
                }

                private global::System.Action<global::Minimal.Mvvm.IAsyncCommand<global::Minimal.Mvvm.ViewModelBase?>?>? _changeActiveViewModelCommandChangedCallback;
                private global::Minimal.Mvvm.IAsyncCommand<global::Minimal.Mvvm.ViewModelBase?>? _changeActiveViewModelCommand;
                [global::System.Text.Json.Serialization.JsonIgnore]
                public global::Minimal.Mvvm.IAsyncCommand<global::Minimal.Mvvm.ViewModelBase?>? ChangeActiveViewModelCommand
                {
                    get => _changeActiveViewModelCommand;
                    private set => SetProperty(ref _changeActiveViewModelCommand, value, _changeActiveViewModelCommandChangedCallback ??= OnChangeActiveViewModelCommandChanged, global::Minimal.Mvvm.EventArgsCache.ChangeActiveViewModelCommandPropertyChanged);
                }
            }
            """ ),
    ];
}
