namespace NuExt.Minimal.Mvvm.SourceGenerator.Tests;

internal partial class Commands
{
    public static List<(string fileName, string hintName, string source, string expected, (string hintName, string expected)[] additionalFiles)> UseCommandManagerSources =
    [
        (
            fileName: "MyViewModel.cs",
            hintName: "MyViewModel.g.cs",
            source : """
            using Minimal.Mvvm;
            using System.Windows.Input;

            public partial class MyViewModel : ViewModelBase
            {
                [Notify, UseCommandManager] private ICommand? _commandICommand;

                [Notify, UseCommandManager] private IRelayCommand? _commandIRelayCommand;
                [Notify, UseCommandManager] private IRelayCommand<bool>? _commandIRelayCommandT;
                [Notify, UseCommandManager] private IAsyncCommand? _commandIAsyncCommand;
                [Notify, UseCommandManager] private IAsyncCommand<bool>? _commandIAsyncCommandT;

                [Notify, UseCommandManager] private RelayCommand? _commandRelayCommand;
                [Notify, UseCommandManager] private RelayCommand<bool>? _commandRelayCommandT;
                [Notify, UseCommandManager] private AsyncCommand? _commandAsyncCommand;
                [Notify, UseCommandManager] private AsyncCommand<bool>? _commandAsyncCommandT;
            }
            """,
            expected : """
            // <auto-generated>
            //     Auto-generated by [GeneratorName] [GeneratorVersion]
            // </auto-generated>
            
            #nullable enable
            
            partial class MyViewModel
            {
                public global::System.Windows.Input.ICommand? CommandICommand
                {
                    get => _commandICommand;
                    set => SetProperty(ref _commandICommand, value, global::Minimal.Mvvm.EventArgsCache.CommandICommandPropertyChanged);
                }

                public global::Minimal.Mvvm.IRelayCommand? CommandIRelayCommand
                {
                    get => _commandIRelayCommand;
                    set
                    {
                        if (SetProperty(ref _commandIRelayCommand, value, global::Minimal.Mvvm.EventArgsCache.CommandIRelayCommandPropertyChanged, out var oldValue))
                        {
                            global::Minimal.Mvvm.RequerySuggestedEventManager.RemoveHandler(oldValue);
                            global::Minimal.Mvvm.RequerySuggestedEventManager.AddHandler(value);
                        }
                    }
                }

                public global::Minimal.Mvvm.IRelayCommand<bool>? CommandIRelayCommandT
                {
                    get => _commandIRelayCommandT;
                    set
                    {
                        if (SetProperty(ref _commandIRelayCommandT, value, global::Minimal.Mvvm.EventArgsCache.CommandIRelayCommandTPropertyChanged, out var oldValue))
                        {
                            global::Minimal.Mvvm.RequerySuggestedEventManager.RemoveHandler(oldValue);
                            global::Minimal.Mvvm.RequerySuggestedEventManager.AddHandler(value);
                        }
                    }
                }

                public global::Minimal.Mvvm.IAsyncCommand? CommandIAsyncCommand
                {
                    get => _commandIAsyncCommand;
                    set
                    {
                        if (SetProperty(ref _commandIAsyncCommand, value, global::Minimal.Mvvm.EventArgsCache.CommandIAsyncCommandPropertyChanged, out var oldValue))
                        {
                            global::Minimal.Mvvm.RequerySuggestedEventManager.RemoveHandler(oldValue);
                            global::Minimal.Mvvm.RequerySuggestedEventManager.AddHandler(value);
                        }
                    }
                }

                public global::Minimal.Mvvm.IAsyncCommand<bool>? CommandIAsyncCommandT
                {
                    get => _commandIAsyncCommandT;
                    set
                    {
                        if (SetProperty(ref _commandIAsyncCommandT, value, global::Minimal.Mvvm.EventArgsCache.CommandIAsyncCommandTPropertyChanged, out var oldValue))
                        {
                            global::Minimal.Mvvm.RequerySuggestedEventManager.RemoveHandler(oldValue);
                            global::Minimal.Mvvm.RequerySuggestedEventManager.AddHandler(value);
                        }
                    }
                }

                public global::Minimal.Mvvm.RelayCommand? CommandRelayCommand
                {
                    get => _commandRelayCommand;
                    set
                    {
                        if (SetProperty(ref _commandRelayCommand, value, global::Minimal.Mvvm.EventArgsCache.CommandRelayCommandPropertyChanged, out var oldValue))
                        {
                            global::Minimal.Mvvm.RequerySuggestedEventManager.RemoveHandler(oldValue);
                            global::Minimal.Mvvm.RequerySuggestedEventManager.AddHandler(value);
                        }
                    }
                }

                public global::Minimal.Mvvm.RelayCommand<bool>? CommandRelayCommandT
                {
                    get => _commandRelayCommandT;
                    set
                    {
                        if (SetProperty(ref _commandRelayCommandT, value, global::Minimal.Mvvm.EventArgsCache.CommandRelayCommandTPropertyChanged, out var oldValue))
                        {
                            global::Minimal.Mvvm.RequerySuggestedEventManager.RemoveHandler(oldValue);
                            global::Minimal.Mvvm.RequerySuggestedEventManager.AddHandler(value);
                        }
                    }
                }

                public global::Minimal.Mvvm.AsyncCommand? CommandAsyncCommand
                {
                    get => _commandAsyncCommand;
                    set
                    {
                        if (SetProperty(ref _commandAsyncCommand, value, global::Minimal.Mvvm.EventArgsCache.CommandAsyncCommandPropertyChanged, out var oldValue))
                        {
                            global::Minimal.Mvvm.RequerySuggestedEventManager.RemoveHandler(oldValue);
                            global::Minimal.Mvvm.RequerySuggestedEventManager.AddHandler(value);
                        }
                    }
                }

                public global::Minimal.Mvvm.AsyncCommand<bool>? CommandAsyncCommandT
                {
                    get => _commandAsyncCommandT;
                    set
                    {
                        if (SetProperty(ref _commandAsyncCommandT, value, global::Minimal.Mvvm.EventArgsCache.CommandAsyncCommandTPropertyChanged, out var oldValue))
                        {
                            global::Minimal.Mvvm.RequerySuggestedEventManager.RemoveHandler(oldValue);
                            global::Minimal.Mvvm.RequerySuggestedEventManager.AddHandler(value);
                        }
                    }
                }
            }

            """,
            additionalFiles: [("Minimal.Mvvm.EventArgsCache.g.cs", """
            // <auto-generated>
            //     Auto-generated by [GeneratorName] [GeneratorVersion]
            // </auto-generated>
            
            #nullable enable

            namespace Minimal.Mvvm
            {
                internal static partial class EventArgsCache
                {
                    internal static readonly global::System.ComponentModel.PropertyChangedEventArgs CommandAsyncCommandPropertyChanged = new global::System.ComponentModel.PropertyChangedEventArgs("CommandAsyncCommand");
                    internal static readonly global::System.ComponentModel.PropertyChangedEventArgs CommandAsyncCommandTPropertyChanged = new global::System.ComponentModel.PropertyChangedEventArgs("CommandAsyncCommandT");
                    internal static readonly global::System.ComponentModel.PropertyChangedEventArgs CommandIAsyncCommandPropertyChanged = new global::System.ComponentModel.PropertyChangedEventArgs("CommandIAsyncCommand");
                    internal static readonly global::System.ComponentModel.PropertyChangedEventArgs CommandIAsyncCommandTPropertyChanged = new global::System.ComponentModel.PropertyChangedEventArgs("CommandIAsyncCommandT");
                    internal static readonly global::System.ComponentModel.PropertyChangedEventArgs CommandICommandPropertyChanged = new global::System.ComponentModel.PropertyChangedEventArgs("CommandICommand");
                    internal static readonly global::System.ComponentModel.PropertyChangedEventArgs CommandIRelayCommandPropertyChanged = new global::System.ComponentModel.PropertyChangedEventArgs("CommandIRelayCommand");
                    internal static readonly global::System.ComponentModel.PropertyChangedEventArgs CommandIRelayCommandTPropertyChanged = new global::System.ComponentModel.PropertyChangedEventArgs("CommandIRelayCommandT");
                    internal static readonly global::System.ComponentModel.PropertyChangedEventArgs CommandRelayCommandPropertyChanged = new global::System.ComponentModel.PropertyChangedEventArgs("CommandRelayCommand");
                    internal static readonly global::System.ComponentModel.PropertyChangedEventArgs CommandRelayCommandTPropertyChanged = new global::System.ComponentModel.PropertyChangedEventArgs("CommandRelayCommandT");
                }
            }

            """)]
        ),
        (
            fileName: "MyViewModel.cs",
            hintName: "MyViewModel.g.cs",
        source : """
        using Minimal.Mvvm;
        using System.Threading;
        using System.Threading.Tasks;
        
        public partial class MyViewModel : ViewModelBase
        {
            [Notify(Setter = AccessModifier.Private, CallbackName=nameof(Stub))]
            [AlsoNotify(nameof(IsOpenAvailable))]
            [UseCommandManager]
            private async Task OpenAsync(CancellationToken ct)
            {
                await Task.Delay(1000);
            }

            [Notify(Setter = AccessModifier.Private)]
            [UseCommandManager]
            private async Task CloseAsync(bool force, CancellationToken ct)
            {
                await Task.Delay(1000);
            }

            [Notify(Setter = AccessModifier.Private)]
            [AlsoNotify(nameof(IsOpenAvailable), nameof(CloseCommand))]
            [UseCommandManager]
            private void Hide(CancellationToken ct)
            {
            }

            public bool IsOpenAvailable => OpenCommand != null;

            [UseCommandManager]
            private void Stub()
            {
            }
        }
        """, 
        expected: """
        // <auto-generated>
        //     Auto-generated by [GeneratorName] [GeneratorVersion]
        // </auto-generated>
        
        #nullable enable

        partial class MyViewModel
        {
            private global::System.Action? _openCommandChangedCallback;

            private global::Minimal.Mvvm.IAsyncCommand? _openCommand;
            public global::Minimal.Mvvm.IAsyncCommand? OpenCommand
            {
                get => _openCommand;
                private set
                {
                    if (SetProperty(ref _openCommand, value, _openCommandChangedCallback ??= Stub, global::Minimal.Mvvm.EventArgsCache.OpenCommandPropertyChanged, out var oldValue))
                    {
                        RaisePropertyChanged(global::Minimal.Mvvm.EventArgsCache.IsOpenAvailablePropertyChanged);
                        global::Minimal.Mvvm.RequerySuggestedEventManager.RemoveHandler(oldValue);
                        global::Minimal.Mvvm.RequerySuggestedEventManager.AddHandler(value);
                    }
                }
            }

            private global::Minimal.Mvvm.IAsyncCommand<bool>? _closeCommand;
            public global::Minimal.Mvvm.IAsyncCommand<bool>? CloseCommand
            {
                get => _closeCommand;
                private set
                {
                    if (SetProperty(ref _closeCommand, value, global::Minimal.Mvvm.EventArgsCache.CloseCommandPropertyChanged, out var oldValue))
                    {
                        global::Minimal.Mvvm.RequerySuggestedEventManager.RemoveHandler(oldValue);
                        global::Minimal.Mvvm.RequerySuggestedEventManager.AddHandler(value);
                    }
                }
            }

            private global::Minimal.Mvvm.IRelayCommand<global::System.Threading.CancellationToken>? _hideCommand;
            public global::Minimal.Mvvm.IRelayCommand<global::System.Threading.CancellationToken>? HideCommand
            {
                get => _hideCommand;
                private set
                {
                    if (SetProperty(ref _hideCommand, value, global::Minimal.Mvvm.EventArgsCache.HideCommandPropertyChanged, out var oldValue))
                    {
                        RaisePropertiesChanged(global::Minimal.Mvvm.EventArgsCache.IsOpenAvailablePropertyChanged, global::Minimal.Mvvm.EventArgsCache.CloseCommandPropertyChanged);
                        global::Minimal.Mvvm.RequerySuggestedEventManager.RemoveHandler(oldValue);
                        global::Minimal.Mvvm.RequerySuggestedEventManager.AddHandler(value);
                    }
                }
            }
        }

        """,
        additionalFiles: [("Minimal.Mvvm.EventArgsCache.g.cs", """
            // <auto-generated>
            //     Auto-generated by [GeneratorName] [GeneratorVersion]
            // </auto-generated>
            
            #nullable enable

            namespace Minimal.Mvvm
            {
                internal static partial class EventArgsCache
                {
                    internal static readonly global::System.ComponentModel.PropertyChangedEventArgs CloseCommandPropertyChanged = new global::System.ComponentModel.PropertyChangedEventArgs("CloseCommand");
                    internal static readonly global::System.ComponentModel.PropertyChangedEventArgs HideCommandPropertyChanged = new global::System.ComponentModel.PropertyChangedEventArgs("HideCommand");
                    internal static readonly global::System.ComponentModel.PropertyChangedEventArgs IsOpenAvailablePropertyChanged = new global::System.ComponentModel.PropertyChangedEventArgs("IsOpenAvailable");
                    internal static readonly global::System.ComponentModel.PropertyChangedEventArgs OpenCommandPropertyChanged = new global::System.ComponentModel.PropertyChangedEventArgs("OpenCommand");
                }
            }

            """)]
        )
    ];
   
}
