namespace NuExt.Minimal.Mvvm.SourceGenerator.Tests
{
    internal static partial class CustomAttributes
    {
        public static List<(string source, string? expected)> Sources =
        [
            (
                source : """
                using Minimal.Mvvm;

                public partial class MyModel : BindableBase
                {
                    /// <summary>
                    /// Gets or sets the model name.
                    /// </summary>
                    [CustomAttribute("[global::System.Text.Json.Serialization.JsonPropertyName(\"MyName\")]")]
                    [Notify, CustomAttribute("[global::System.Text.Json.Serialization.JsonPropertyOrder(1)]")]
                    private string _name = null!;

                    [Notify, CustomAttribute("[global::System.Text.Json.Serialization.JsonIgnore]")]
                    private string? _description;
                }
                """,
                expected : """
                // <auto-generated>
                //     Auto-generated by [GeneratorName] [GeneratorVersion]
                // </auto-generated>

                #nullable enable

                partial class MyModel
                {
                    /// <summary>
                    /// Gets or sets the model name.
                    /// </summary>
                    [global::System.Text.Json.Serialization.JsonPropertyName("MyName")]
                    [global::System.Text.Json.Serialization.JsonPropertyOrder(1)]
                    public string Name
                    {
                        get => _name;
                        set => SetProperty(ref _name, value, global::Minimal.Mvvm.EventArgsCache.NamePropertyChanged);
                    }

                    [global::System.Text.Json.Serialization.JsonIgnore]
                    public string? Description
                    {
                        get => _description;
                        set => SetProperty(ref _description, value, global::Minimal.Mvvm.EventArgsCache.DescriptionPropertyChanged);
                    }
                }
                """ ),
        ];
    }
}
