namespace NuExt.Minimal.Mvvm.SourceGenerator.Tests;

internal static class LocalizeAttributes
{
    public static List<(string source, string? expected)> Sources =
    [
        (
            source : """
            using Minimal.Mvvm;

            [Localize("local.en-US.json")]
            public static partial class MyLoc
            {
            }
            """,
            expected : """
            // <auto-generated>
            //     Auto-generated by [GeneratorName] [GeneratorVersion]
            // </auto-generated>

            #nullable enable

            partial class MyLoc
            {
                /// <summary>
                /// Looks up a localized string similar to An error has occurred in {0}:{1}.
                /// </summary>
                public static string An_error_has_occurred_in_Arg1_Arg2 { get; set; } = "An error has occurred in {0}:{1}";

                /// <summary>
                /// Looks up a localized string similar to My Description.
                /// </summary>
                public static string Description { get; set; } = "My Description";

                /// <summary>
                /// Looks up a localized string similar to This &amp; that &lt; those &gt; "these" 'others' \ here and there\r\n\\.
                /// </summary>
                public static string Escaped { get; set; } = "This & that < those > \"these\" 'others' \\ here and there\r\n\\\\";

                /// <summary>
                /// Looks up a localized string similar to My Name.
                /// </summary>
                public static string Name { get; set; } = "My Name";
            }
            """ ),
    ];
}
