using Minimal.Mvvm.SourceGenerator;

namespace NuExt.Minimal.Mvvm.SourceGenerator.Tests
{
    internal class NotifyDataErrorInfoAttributes
    {
        public static List<(string source, string? expected)> Sources =
        [
            (
                source : """
                         using Minimal.Mvvm;

                         [NotifyDataErrorInfo]
                         public partial class MyModel : System.ComponentModel.INotifyPropertyChanged
                         {
                             [Notify]
                             private string _name = null!;
                         }
                         """,
                expected : null
            ),
            (
                source : """
                         using Minimal.Mvvm;

                         [NotifyDataErrorInfo]
                         public partial class MyModel : BindableBase, System.ComponentModel.INotifyDataErrorInfo
                         {
                             [Notify]
                             private string _name = null!;
                         }
                         """,
                expected : """
                            // <auto-generated>
                            //     Auto-generated by [GeneratorName] [GeneratorVersion]
                            // </auto-generated>

                            #nullable enable

                            partial class MyModel
                            {
                                public string Name
                                {
                                    get => _name;
                                    set => SetProperty(ref _name, value, global::Minimal.Mvvm.EventArgsCache.NamePropertyChanged);
                                }


                            """
                            + NotifyDataErrorInfoGenerator.GetCodeSource(1, "?") +
                            """
                            }
                            """
                           ),
        ];
    }
}
