namespace NuExt.Minimal.Mvvm.SourceGenerator.Tests
{
    internal static partial class PartialProperties
    {
        public static List<(string source, string? expected)> Sources =
       [
            (
                source : """
                using Minimal.Mvvm;

                public partial class MyModel : BindableBase
                {
                    [Notify]
                    public partial string? Name { get; set; }

                    [Notify]
                    private partial string? Description { get; set; }
                }
                """,
                expected : """
                // <auto-generated>
                //     Auto-generated by [GeneratorName] [GeneratorVersion]
                // </auto-generated>

                #nullable enable

                partial class MyModel
                {
                    private string? _name;
                    public partial string? Name
                    {
                        get => _name;
                        set => SetProperty(ref _name, value, global::Minimal.Mvvm.EventArgsCache.NamePropertyChanged);
                    }

                    private string? _description;
                    private partial string? Description
                    {
                        get => _description;
                        set => SetProperty(ref _description, value, global::Minimal.Mvvm.EventArgsCache.DescriptionPropertyChanged);
                    }
                }
                """ ),
            (
                source : """
                using Minimal.Mvvm;

                public partial class MyModel : ViewModelBase
                {
                    [Notify(Setter = AccessModifier.Private)]
                    public partial string? Name { get; private set; }

                    [Notify(Getter = AccessModifier.Internal)]
                    public partial string? Description { internal get; set; }
                }
                """,
                expected: """
                // <auto-generated>
                //     Auto-generated by [GeneratorName] [GeneratorVersion]
                // </auto-generated>

                #nullable enable

                partial class MyModel
                {
                    private string? _name;
                    public partial string? Name
                    {
                        get => _name;
                        private set => SetProperty(ref _name, value, global::Minimal.Mvvm.EventArgsCache.NamePropertyChanged);
                    }

                    private string? _description;
                    public partial string? Description
                    {
                        internal get => _description;
                        set => SetProperty(ref _description, value, global::Minimal.Mvvm.EventArgsCache.DescriptionPropertyChanged);
                    }
                }
                """),
            (
                source: """
                using Minimal.Mvvm;

                public partial class MyModel : ViewModelBase
                {
                    [Notify(Setter = AccessModifier.ProtectedInternal)]
                    public partial string? Name { get; protected internal set; }

                    [Notify(Getter = AccessModifier.Internal, Setter = AccessModifier.Private)]
                    internal partial string? Description{ get; private set;}
                }
                """,
                expected: """
                // <auto-generated>
                //     Auto-generated by [GeneratorName] [GeneratorVersion]
                // </auto-generated>

                #nullable enable

                partial class MyModel
                {
                    private string? _name;
                    public partial string? Name
                    {
                        get => _name;
                        protected internal set => SetProperty(ref _name, value, global::Minimal.Mvvm.EventArgsCache.NamePropertyChanged);
                    }

                    private string? _description;
                    internal partial string? Description
                    {
                        get => _description;
                        private set => SetProperty(ref _description, value, global::Minimal.Mvvm.EventArgsCache.DescriptionPropertyChanged);
                    }
                }
                """),
            (
                source: """
                using Minimal.Mvvm;

                public partial class MyModel : ViewModelBase
                {
                    [Notify(Getter = AccessModifier.Private, Setter = AccessModifier.ProtectedInternal)]
                    protected internal partial string? Name { private get; set; }

                    [Notify(Getter = AccessModifier.Internal, Setter = AccessModifier.PrivateProtected)]
                    internal partial string? Description { get; private protected set; }
                }
                """,
                expected: """
                // <auto-generated>
                //     Auto-generated by [GeneratorName] [GeneratorVersion]
                // </auto-generated>

                #nullable enable

                partial class MyModel
                {
                    private string? _name;
                    protected internal partial string? Name
                    {
                        private get => _name;
                        set => SetProperty(ref _name, value, global::Minimal.Mvvm.EventArgsCache.NamePropertyChanged);
                    }

                    private string? _description;
                    internal partial string? Description
                    {
                        get => _description;
                        private protected set => SetProperty(ref _description, value, global::Minimal.Mvvm.EventArgsCache.DescriptionPropertyChanged);
                    }
                }
                """),
            (
                source: """
                using Minimal.Mvvm;

                public partial class MyModel : ViewModelBase
                {
                    [Notify(Getter = AccessModifier.Private, Setter = AccessModifier.Private)]
                    private partial string? Name { get; set; }

                    [Notify(Getter = AccessModifier.Private, Setter = AccessModifier.Internal)]
                    internal partial string? Description { private get; set; }
                }
                """,
                expected: """
                // <auto-generated>
                //     Auto-generated by [GeneratorName] [GeneratorVersion]
                // </auto-generated>

                #nullable enable

                partial class MyModel
                {
                    private string? _name;
                    private partial string? Name
                    {
                        get => _name;
                        set => SetProperty(ref _name, value, global::Minimal.Mvvm.EventArgsCache.NamePropertyChanged);
                    }

                    private string? _description;
                    internal partial string? Description
                    {
                        private get => _description;
                        set => SetProperty(ref _description, value, global::Minimal.Mvvm.EventArgsCache.DescriptionPropertyChanged);
                    }
                }
                """),
            (
                source: """
                using Minimal.Mvvm;

                public partial class MyModel : ViewModelBase
                {
                    [Notify(Getter = AccessModifier.Private, Setter = AccessModifier.Public)]
                    public partial string? Name { private get; set; }

                    [Notify(Getter = AccessModifier.Private, Setter = AccessModifier.PrivateProtected)]
                    private protected partial string? Description { private get; set; }
                }
                """,
                expected: """
                // <auto-generated>
                //     Auto-generated by [GeneratorName] [GeneratorVersion]
                // </auto-generated>

                #nullable enable

                partial class MyModel
                {
                    private string? _name;
                    public partial string? Name
                    {
                        private get => _name;
                        set => SetProperty(ref _name, value, global::Minimal.Mvvm.EventArgsCache.NamePropertyChanged);
                    }

                    private string? _description;
                    private protected partial string? Description
                    {
                        private get => _description;
                        set => SetProperty(ref _description, value, global::Minimal.Mvvm.EventArgsCache.DescriptionPropertyChanged);
                    }
                }
                """),
            (
                source: """
                using Minimal.Mvvm;

                public partial class MyModel : ViewModelBase
                {
                    [Notify(Getter = AccessModifier.Internal, Setter = AccessModifier.Protected)]
                    protected internal partial string? Name { get; protected set; }

                    [Notify(Getter = AccessModifier.Protected, Setter = AccessModifier.Internal)]
                    protected internal partial string? Description{ get; internal set; }
                }
                """,
                expected: """
                // <auto-generated>
                //     Auto-generated by [GeneratorName] [GeneratorVersion]
                // </auto-generated>

                #nullable enable

                partial class MyModel
                {
                    private string? _name;
                    protected internal partial string? Name
                    {
                        get => _name;
                        protected set => SetProperty(ref _name, value, global::Minimal.Mvvm.EventArgsCache.NamePropertyChanged);
                    }

                    private string? _description;
                    protected internal partial string? Description
                    {
                        get => _description;
                        internal set => SetProperty(ref _description, value, global::Minimal.Mvvm.EventArgsCache.DescriptionPropertyChanged);
                    }
                }
                """),
            (
                source: """
                using Minimal.Mvvm;

                public partial class MyModel : ViewModelBase
                {
                    [Notify(Getter = AccessModifier.ProtectedInternal, Setter = AccessModifier.Protected)]
                    protected internal partial string? Name { get; protected set; }

                    [Notify(Getter = AccessModifier.ProtectedInternal, Setter = AccessModifier.Internal)]
                    protected internal partial string? Description { get; internal set; }
                }
                """,
                expected: """
                // <auto-generated>
                //     Auto-generated by [GeneratorName] [GeneratorVersion]
                // </auto-generated>

                #nullable enable

                partial class MyModel
                {
                    private string? _name;
                    protected internal partial string? Name
                    {
                        get => _name;
                        protected set => SetProperty(ref _name, value, global::Minimal.Mvvm.EventArgsCache.NamePropertyChanged);
                    }

                    private string? _description;
                    protected internal partial string? Description
                    {
                        get => _description;
                        internal set => SetProperty(ref _description, value, global::Minimal.Mvvm.EventArgsCache.DescriptionPropertyChanged);
                    }
                }
                """),
            (
                source: """
                using Minimal.Mvvm;

                public partial class MyModel : ViewModelBase
                {
                    [Notify(Getter = AccessModifier.Internal, Setter = AccessModifier.ProtectedInternal)]
                    protected internal partial string? Name { internal get; set; }

                    [Notify(Getter = AccessModifier.Protected, Setter = AccessModifier.ProtectedInternal)]
                    protected internal partial string? Description { protected get; set; }
                }
                """,
                expected: """
                // <auto-generated>
                //     Auto-generated by [GeneratorName] [GeneratorVersion]
                // </auto-generated>

                #nullable enable

                partial class MyModel
                {
                    private string? _name;
                    protected internal partial string? Name
                    {
                        internal get => _name;
                        set => SetProperty(ref _name, value, global::Minimal.Mvvm.EventArgsCache.NamePropertyChanged);
                    }

                    private string? _description;
                    protected internal partial string? Description
                    {
                        protected get => _description;
                        set => SetProperty(ref _description, value, global::Minimal.Mvvm.EventArgsCache.DescriptionPropertyChanged);
                    }
                }
                """),
        ];
    }
}
